[package]
name = "chipioindustries/leaky-bucket"
description = "A rate limiter with a buffer."
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Llama = "freddylist/llama@1.1.1"
Signal = "chipioindustries/signal@1.0.3"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"